spring:
  application:
    name: IngSw2024-jsp-only
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 
    url: jdbc:mysql://localhost:3306/cc24
    username: 
  jpa:
    hibernate:
      ddl-auto:
        update
      dialect:
        org.hibernate.dialect.MySQL8Dialect
